/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CrmjustformeDashboard {}
  interface CrmjustformeEvents {}
  interface CrmjustformePeople {}
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLCrmjustformeDashboardElement extends Components.CrmjustformeDashboard, HTMLStencilElement {}
  var HTMLCrmjustformeDashboardElement: {
    prototype: HTMLCrmjustformeDashboardElement;
    new (): HTMLCrmjustformeDashboardElement;
  };

  interface HTMLCrmjustformeEventsElement extends Components.CrmjustformeEvents, HTMLStencilElement {}
  var HTMLCrmjustformeEventsElement: {
    prototype: HTMLCrmjustformeEventsElement;
    new (): HTMLCrmjustformeEventsElement;
  };

  interface HTMLCrmjustformePeopleElement extends Components.CrmjustformePeople, HTMLStencilElement {}
  var HTMLCrmjustformePeopleElement: {
    prototype: HTMLCrmjustformePeopleElement;
    new (): HTMLCrmjustformePeopleElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'crmjustforme-dashboard': HTMLCrmjustformeDashboardElement;
    'crmjustforme-events': HTMLCrmjustformeEventsElement;
    'crmjustforme-people': HTMLCrmjustformePeopleElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface CrmjustformeDashboard extends JSXBase.HTMLAttributes<HTMLCrmjustformeDashboardElement> {}
  interface CrmjustformeEvents extends JSXBase.HTMLAttributes<HTMLCrmjustformeEventsElement> {}
  interface CrmjustformePeople extends JSXBase.HTMLAttributes<HTMLCrmjustformePeopleElement> {}
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'crmjustforme-dashboard': CrmjustformeDashboard;
    'crmjustforme-events': CrmjustformeEvents;
    'crmjustforme-people': CrmjustformePeople;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


